server:
  port: 8080
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop

---

system-messages:
  error:
    general-transactional-error: "Se produjo un en la transacción."
    data-integrity-error: "Se produjo un error de integridad de datos."
    email-constraint-error: "El correo ya registrado."
